### ISSUE TITLE
当前目录下，package.json会干扰命令执行

### ISSUE THREAD

**Issue by luckyxiaomo** [haochuan9421/coscmd#2]
我在加载配置文件时，我配置文件的同级目录下的package.json 部分如下

{
  "name": "vite-project",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  
  
  这个type = module 时，命令无法执行，需要改成 commonjs
  
  有三个解决办法：

1.  重命名文件: 将 cos.config.js 文件重命名为 cos.config.cjs，这样它就会被视为 CommonJS 模块文件。
2. 修改 package.json 中的 type 属性: 将 type 属性从 "module" 改为 "commonjs"，这样所有的 .js 文件都会被视为 CommonJS 模块文件。
3. 在 coscmd 模块中使用动态导入: 如果你有修改 coscmd 模块的权限，可以尝试在代码中使用动态导入 (import() ) 来加载 cos.config.js 文件。

但是，肯定不能改项目的type。建议支持 cos.config.cjs 配置文件。

**Comment by luckyxiaomo** [comment]
我临时的解决办法，就是将文件放到根目录下。

**Comment by haochuan9421** [comment]
安装 v1.0.8，使用 `cos.config.cjs`
